# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: WSO2 API Manager deployment with WSO2 Micro Integrator

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic Configuration
        Parameters:
          - AWSAccessKeyId
          - AWSAccessKeySecret
          - WUMUsername
          - WUMPassword
          - DBUsername
          - DBPassword
          - KeyPairName
          - CertificateName
      - Label:
          default: Advanced Configuration
        Parameters:
          - DB
          - JDK
          - OperatingSystem
    ParameterLabels:
      AWSAccessKeyId:
        default: AWS Access Key ID
      AWSAccessKeySecret:
        default: AWS Access Secret Key
      WUMUsername:
        default: WSO2 Username
      WUMPassword:
        default: WSO2 Password
      CertificateName:
        default: SSL Certificate Name
      CustomUserData:
        default: Custom User Data
      DB:
        default: Database
      DBUsername:
        default: Database Username
      DBPassword:
        default: Database Password
      JDK:
        default: JDK
      KeyPairName:
        default: Key Pair Name
      OperatingSystem:
        default: Operating System
      WSO2InstanceType:
        default: Instance type for Identity Server deployment

Parameters:
  AWSAccessKeyId:
    Type: String

  AWSAccessKeySecret:
    Type: String
    NoEcho: true

  WUMUsername:
    Type: String
    Default: ""
  WUMPassword:
    Type: String
    Default: ""
    NoEcho: true

  CertificateName:
    Description: A valid SSL certificate used for HTTPS
    Type: String
    MinLength: 1

  DBUsername:
    Type: String
    MinLength: 4
    AllowedPattern: '[A-Za-z0-9\-]+'

  DBPassword:
    Type: String
    MinLength: 8
    NoEcho: true

  DB:
    Description: Choose preffered Database from the list
    Type: String
    Default: MySQL-5.7
    AllowedValues:
      - MySQL-5.7
      - Postgres-9.6
      - Postgres-10.5
      - Oracle-SE1-11.2
      - Oracle-SE2-12.1
      - SQLServer-SE-13.00
      - SQLServer-SE-14.00

  JDK:
    Description: Choose preffered JDK from the list
    Type: String
    Default: "OPEN_JDK8"
    AllowedValues:
      - "OPEN_JDK8"
      - "ORACLE_JDK8"
      - "CORRETTO_JDK8"
      - "ADOPT_OPEN_JDK11"

  KeyPairName:
    Description: The private key used to log in to instances through SSH
    Type: AWS::EC2::KeyPair::KeyName

  OperatingSystem:
    Description: Operating System for API Manager deployment
    Type: String
    Default: Ubuntu1804
    AllowedValues:
      - Ubuntu1804
      - CentOS7

Resources:
  WSO2Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/apim-4.0.0-cfn/network.yaml
      TimeoutInMinutes: '30'
      Parameters:
        KeyPairName: !Ref KeyPairName
      Tags:
        - Key: Name
          Value: WSO2Network

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/apim-4.0.0-cfn/database.yaml
      TimeoutInMinutes: '30'
      Parameters:
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DB: !Ref DB
        DBAllocationStorage: 20
        WSO2VPC: !GetAtt WSO2Network.Outputs.VPC
        WSO2PrivateSubnet1: !GetAtt WSO2Network.Outputs.PrivateSubnet1
        WSO2PrivateSubnet2: !GetAtt WSO2Network.Outputs.PrivateSubnet2
      Tags:
        - Key: Name
          Value: WSO2Database

  WSO2APIManagerSetup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/apim-4.0.0-cfn/pattern-1.yaml
      TimeoutInMinutes: '30'
      Parameters:
        AWSAccessKeyId: !Ref AWSAccessKeyId
        AWSAccessKeySecret: !Ref AWSAccessKeySecret
        WUMUsername: !Ref WUMUsername
        WUMPassword: !Ref WUMPassword
        CertificateName: !Ref CertificateName
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        DB: !Ref DB
        JDK: !Ref JDK
        KeyPairName: !Ref KeyPairName
        OperatingSystem: !Ref OperatingSystem
        WSO2APIMDBInstanceEndpointAddress: !GetAtt Database.Outputs.WSO2APIMDBInstanceEndpointAddress
        WSO2APIMDBInstanceEndpointPort: !GetAtt Database.Outputs.WSO2APIMDBInstanceEndpointPort
        WSO2APIMVPC: !GetAtt WSO2Network.Outputs.VPC
        WSO2APIMPrivateSubnet1: !GetAtt WSO2Network.Outputs.PrivateSubnet1
        WSO2APIMPrivateSubnet2: !GetAtt WSO2Network.Outputs.PrivateSubnet2
        WSO2APIMPublicSubnet1: !GetAtt WSO2Network.Outputs.PublicSubnet1
        WSO2APIMPublicSubnet2: !GetAtt WSO2Network.Outputs.PublicSubnet2
      Tags:
        - Key: Name
          Value: WSO2APIManagerSetup

Outputs:
  CarbonServerUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.CarbonServerUrl
    Description: Carbon Server URL

  MgtConsoleUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.MgtConsoleUrl
    Description: API Manager Management Console URL

  PublisherUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.PublisherUrl
    Description: API Manager service publisher URL

  DevPortalUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.DevPortalUrl
    Description: API Manager service devportal URL

  AdminUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.AdminUrl
    Description: API Manager service admin URL

  KeyManagerUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.KeyManagerUrl
    Description: API Manager keymanager service admin URL

  GatewayHttpsUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.GatewayHttpsUrl
    Description: API Manager HTTPS Gateway endpoint

  GatewayHttpUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.GatewayHttpUrl
    Description: API Manager HTTP Gateway endpoint

  MIPassThroughHttpsUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.MIPassThroughHttpsUrl
    Description: MI HTTPS Pass Through URL

  MIPassThroughHttpUrl:
    Value: !GetAtt WSO2APIManagerSetup.Outputs.MIPassThroughHttpUrl
    Description: MI HTTP Pass Through URL

  WSO2APIMDBInstanceEndpointAddress:
    Value: !GetAtt Database.Outputs.WSO2APIMDBInstanceEndpointAddress
    Description: Identity Server DB Instance Endpoint Address
    Export:
      Name: WSO2APIMDBInstanceEndpointAddress

  WSO2APIMDBInstanceEndpointPort:
    Value: !GetAtt Database.Outputs.WSO2APIMDBInstanceEndpointPort
    Description: Identity Server DB Instance Endpoint Port
    Export:
      Name: WSO2APIMDBInstanceEndpointPort

  PrivateSubnet1:
    Value: !GetAtt WSO2Network.Outputs.PrivateSubnet1
    Description: Private Subnet for PuppetMaster, Prodcut Instance, EFS and the DB
    Export:
      Name: PrivateSubnet1

  PrivateSubnet2:
    Value: !GetAtt WSO2Network.Outputs.PrivateSubnet2
    Description: Private Subnet for Prodcut Instance and the DB
    Export:
      Name: PrivateSubnet2

  PublicSubnet1:
    Value: !GetAtt WSO2Network.Outputs.PublicSubnet1
    Description: Public Subnet for NAT Gateway, Bastion Instance and Load Balancer
    Export:
      Name: PublicSubnet1

  PublicSubnet2:
    Value: !GetAtt WSO2Network.Outputs.PublicSubnet2
    Description: Public Subnet for Load Balancer
    Export:
      Name: PublicSubnet2

  VPC:
    Value: !GetAtt WSO2Network.Outputs.VPC
    Description: VPC
    Export:
      Name: WSO2VPC
